Added cutebg theme

diff --git a/.local/bin/cutebg b/.local/bin/cutebg
--- a/.local/bin/cutebg
+++ b/.local/bin/cutebg
@@ -3,30 +3,34 @@
 shopt -s nullglob
 
 exists() { hash "$@" &>/dev/null; }
-require() { exists "$@" || exit 127; }
-
-require wal rofi feh dunst qtile
+require() {
+    for dep in "$@"; do
+        exists "$dep" || die "Dependency ${dep} is missing. Install it." 127
+    done
+}
 
 main() {
+    require wal feh dunst qtile
+
     get_args "${@}"
 
-    [[ -z "$imgfile" ]] && interactive
+    [[ -z "$img_file" ]] && interactive
 
-    [[ -z "$imgfile" ]] && usage && die "Expected input"
+    [[ -z "$img_file" ]] && usage && die "Expected input" 1
 
-    [[ ! -f "$imgfile" && ! -d "$imgfile" ]] && die "File doesn't exist owo"
+    [[ ! -f "$img_file" && ! -d "$img_file" ]] && die "File doesn't exist owo" 1
 
-    [[ -d "$imgfile" ]] || ! identify "$imgfile" &>/dev/null && die "$imgfile is not an image >w<"
+    [[ -d "$img_file" ]] || ! identify "$img_file" &>/dev/null && die "$img_file is not an image >w<" 1
 
     if exists pywal-spicetify; then
         color_ini_dir="${HOME}/.config/spicetify/Themes/${spice_theme:-text}"
-        [[ ! -d "$color_ini_dir" ]] && die "Theme ${spice_theme} doesn't exist."
+        [[ ! -d "$color_ini_dir" ]] && die "Theme ${spice_theme} doesn't exist." 1
         color_ini="$color_ini_dir/color.ini"
         [[ ! -f $color_ini ]] && printf "; This file was generated by cutebg" >>"$color_ini"
         pywal-spicetify text &>/dev/null
     fi
-    wal --cols16 "${colortheme:-darken}" -i "$imgfile"
-    feh --bg-fill "$imgfile" &>/dev/null
+    wal --cols16 "${colortheme:-darken}" -i "$img_file"
+    feh --bg-fill "$img_file" &>/dev/null
     [[ ! -d "${HOME}/.config/dunst" ]] && mkdir "${HOME}/.config/dunst"
     [[ ! -L "${HOME}/.config/dunst/dunstrc" ]] && ln -s "${HOME}/.cache/wal/dunstrc" "${HOME}/.config/dunst/dunstrc"
     pkill dunst
@@ -54,37 +58,8 @@ HELP_MSG
 
 die() {
     printf "%s\n" "$1"
-    exit 1
+    exit "$2"
 }
-
-#get_args() {
-#    for opt in "$@"; do
-#        shift
-#        case "$opt" in
-#        "--help") set -- "$@" "-h" ;;
-#        "--lighten") set -- "$@" "-l" ;;
-#        "--spice-theme") set -- "$@" "-t" ;;
-#        "--directory") set -- "$@" "-d" ;;
-#        *) set -- "$@" "$opt" ;;
-#        esac
-#    done
-#
-#    while getopts ":hlt:d:" opt; do
-#        case $opt in
-#        h) usage && exit 0 ;;
-#        l) colortheme="lighten" ;;
-#        t) spice_theme=${OPTARG} ;;
-#        d) wal_dir=${OPTARG} ;;
-#        :) die "Option -${OPTARG} requires an argument." ;;
-#        ?) usage && die "Invalid option: -${OPTARG}." ;;
-#        esac
-#    done
-#    echo $#
-#    echo "$OPTIND"
-#    shift $((OPTIND - 1))
-#    echo $#
-#    imgfile="$1"
-#}
 
 get_args() {
     pos_args=()
@@ -106,7 +81,7 @@ get_args() {
                 spice_theme=$val
                 shift 2
             else
-                die "Option $arg requires an argument."
+                die "Option $arg requires an argument." 1
             fi
             ;;
         -d | --directory)
@@ -114,11 +89,11 @@ get_args() {
                 wal_dir=$val
                 shift 2
             else
-                die "Option $arg requires an argument."
+                die "Option $arg requires an argument." 1
             fi
             ;;
         -*)
-            die "Invalid option: $arg"
+            die "Invalid option: $arg" 1
             ;;
         *)
             pos_args+=("$arg")
@@ -129,16 +104,28 @@ get_args() {
 
     set -- "${pos_args[@]}"
 
-    imgfile=$1
+    img_file=$1
 }
 
 interactive() {
+    require rofi magick
+
     wal_dir=${wal_dir:-$HOME/Pictures/Wallpapers}
     cache_dir="${HOME}/.cache/cutebg"
-    rofi_cmd() { rofi -dmenu -i -show-icons -p "  Select Wallpaper"; }
+    monitor_res=$(($(xdpyinfo | awk '/dimensions/{print $2}' | cut -d 'x' -f1) * \
+    14 / $(xdpyinfo | awk '/resolution/{print $2}' | cut -d 'x' -f1)))
+    rofi_override="element-icon{size:${monitor_res}px;}"
+    rofi_theme="$HOME/.config/rofi/themes/cutebg.rasi"
+
+    rofi_cmd() {
+        rofi -dmenu -i -show-icons -p "  Select Wallpaper" \
+            -theme "$rofi_theme" -theme-str "$rofi_override"
+    }
+
     magick_cmd() {
         cache_fname="$2"
-        [[ ! -d "${cache_dir}/${cache_fname%%/*}" ]] && mkdir -p "${cache_dir}/${cache_fname%%/*}"
+        [[ ! -d "${cache_dir}/${cache_fname%%/*}" ]] &&
+            mkdir -p "${cache_dir}/${cache_fname%%/*}"
         cache_f="${cache_dir}/${cache_fname}"
         if [[ ! -f "$cache_f" ]]; then
             magick "$1" -strip -thumbnail 500x500^ -gravity center \
@@ -149,28 +136,31 @@ interactive() {
     [[ ! -d "$cache_dir" ]] && mkdir -p "$cache_dir"
 
     wals=()
-    fullpath=()
+    #fullpath=()
     for entry in "$wal_dir"/*; do
         if [[ -d "$entry" ]]; then
             group="${entry##*/}"
             for file in "$entry"/*; do
                 img="${group}/${file##*/}"
+                #fullpath+=("$file")
                 wals+=("$img")
-                fullpath+=("$file")
                 magick_cmd "$file" "$img"
             done
         else
             img="${entry##*/}"
+            #fullpath+=("$entry")
             wals+=("$img")
-            fullpath+=("$entry")
             magick_cmd "$entry" "$img"
         fi
     done
 
-    imgfile="${wal_dir}/$(
+    img_file="${wal_dir}/$(
         for image in "${wals[@]}"; do
             printf "%s\x00icon\x1f%s\n" "$image" "${cache_dir}/${image}"
         done | rofi_cmd
+        #for i in "${!wals[@]}"; do
+        #    printf "%s\x00icon\x1f%s\n" "${wals[i]}" "${fullpath[i]}"
+        #done | rofi_cmd
     )"
 }
 
